services:
  - type: web
    name: quiz-app
    env: node
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://d15102:Dharmik09@resumeanalyze.dcqthqh.mongodb.net/QuizDB
    # Add health check to ensure the service is running properly
    healthCheckPath: /
    # Increase the initial boot timeout to allow for MongoDB connection
    initialDeployHook: sleep 10
